import '@radix-ui/themes/styles.css';

import {Button, Theme} from "@radix-ui/themes";
import Head from "next/head";
import Navbar from "~/components/navigation/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
      <Theme appearance="light" accentColor="green" grayColor="gray" radius="medium" scaling="90%">
        <Navbar />
        <main className="flex min-h-screen flex-col items-center justify-center">
        <Button>Click me</Button>
        <br></br>
        <form>
      </form>
        </main>
      </Theme>
      </body>
    </>
  );
}
